# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "x_runtime"
  s.version = "0.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["\u{5d14}\u{5ce5}"]
  s.date = "2012-08-25"
  s.description = "\u{7531}\u{4e8e}\u{4f7f}\u{7528}\u{5230}Redis\u{7684}lua script,\u{6240}\u{4ee5}\u{9700}\u{8981}\u{4f60}\u{7684}Redis\u{670d}\u{52a1}\u{652f}\u{6301},redis-server\u{7248}\u{672c}>2.6.x,redis(ruby gem)>3.0.1."
  s.email = "zheng.cuizh@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/x_runtime.rb",
    "lib/x_runtime/data_set.rb",
    "lib/x_runtime/middleware.rb",
    "lib/x_runtime/redis.lua",
    "lib/x_runtime/script.rb",
    "lib/x_runtime/server.rb",
    "lib/x_runtime/template.erb",
    "lib/x_runtime/template.rb",
    "lib/x_runtime/utils.rb",
    "test/client.rb",
    "test/helper.rb",
    "test/server.ru",
    "test/test_x_runtime.rb",
    "x_runtime.gemspec"
  ]
  s.homepage = "http://github.com/charlescui/x_runtime"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "XRuntime\u{662f}\u{4e00}\u{4e2a}Rack\u{7684}middleware,\u{914d}\u{5408}Redis\u{7528}\u{6765}\u{5206}\u{6790}Http Server\u{6bcf}\u{4e2a}URI\u{8bf7}\u{6c42}\u{65f6}\u{957f}"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<redis>, ["~> 3.0.1"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
    else
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<redis>, ["~> 3.0.1"])
      s.add_dependency(%q<sinatra>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<redis>, ["~> 3.0.1"])
    s.add_dependency(%q<sinatra>, [">= 0"])
  end
end

